//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckNameSpace.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICheckService")]
    public interface ICheckService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckService/SendCheck", ReplyAction="http://tempuri.org/ICheckService/SendCheckResponse")]
        string SendCheck(string check);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckService/SendCheck", ReplyAction="http://tempuri.org/ICheckService/SendCheckResponse")]
        System.Threading.Tasks.Task<string> SendCheckAsync(string check);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckService/RequestChecks", ReplyAction="http://tempuri.org/ICheckService/RequestChecksResponse")]
        string RequestChecks(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckService/RequestChecks", ReplyAction="http://tempuri.org/ICheckService/RequestChecksResponse")]
        System.Threading.Tasks.Task<string> RequestChecksAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckServiceChannel : CheckNameSpace.ServiceReference1.ICheckService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckServiceClient : System.ServiceModel.ClientBase<CheckNameSpace.ServiceReference1.ICheckService>, CheckNameSpace.ServiceReference1.ICheckService {
        
        public CheckServiceClient() {
        }
        
        public CheckServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendCheck(string check) {
            return base.Channel.SendCheck(check);
        }
        
        public System.Threading.Tasks.Task<string> SendCheckAsync(string check) {
            return base.Channel.SendCheckAsync(check);
        }
        
        public string RequestChecks(int id) {
            return base.Channel.RequestChecks(id);
        }
        
        public System.Threading.Tasks.Task<string> RequestChecksAsync(int id) {
            return base.Channel.RequestChecksAsync(id);
        }
    }
}
